# **DAY 5: ASSIGNMENT 4 (Numpy)**

# **DATE: 28 MAY 2021**

# **AUTHOR: AAMIR P**

# **REG. ID.: GO_STP_7724**

**1.Import the numpy package under the name np and Print the numpy version and the configuration**

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**2.Create a null vector of size 10**

In [2]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**3.Create Simple 1-D array and check type and check data types in array**


In [3]:
import numpy as np
a=np.array([4,5,6])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


**4.How to find number of dimensions, bytes per element and bytes of memory used?**

In [4]:
import numpy as np
c=np.array([16,10,2000])
print('Dimesion: ',c.ndim)
print('Size of an array: ',c.size)
print("Bytes per element: ",c.itemsize)
print("Bytes of element used: ",c.nbytes)

Dimesion:  1
Size of an array:  3
Bytes per element:  8
Bytes of element used:  24


**5.Create a null vector of size 10 but the fifth value which is 1**


In [5]:
n = np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**6.Create a vector with values ranging from 10 to 49**

In [6]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**7.Reverse a vector (first element becomes last)**

In [7]:
print('Reversed vector: ',np.flip(vector))

Reversed vector:  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**8.Create a 3x3 matrix with values ranging from 0 to 8**


In [8]:
matrix=np.arange(0,9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**9.Find indices of non-zero elements from [1,2,0,0,4,0]**

In [9]:
k = np.array([1,2,0,0,4,0])
print("Orginal data: ",k)
print('Indices of non-zero elements: ')
for i in range(k.size):
  if k[i] != 0:
    print(k[i], end=" ") 

Orginal data:  [1 2 0 0 4 0]
Indices of non-zero elements: 
1 2 4 

**10.Create a 3x3 identity matrix**

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**11.Create a 3x3x3 array with random values**


In [11]:
np.random.random((3,3,3))

array([[[0.22269453, 0.25468269, 0.89580741],
        [0.31391102, 0.98968635, 0.76397459],
        [0.31637665, 0.09464802, 0.61663124]],

       [[0.82081713, 0.10928195, 0.43330733],
        [0.12079724, 0.81968455, 0.77579079],
        [0.32632063, 0.54857219, 0.42195437]],

       [[0.10810242, 0.92076091, 0.51297324],
        [0.56818267, 0.29615092, 0.35108432],
        [0.74285023, 0.602038  , 0.9609133 ]]])

**12.Create a 10x10 array with random values and find the minimum and maximum values**

In [12]:
matrix=np.random.random((10,10))
print(matrix)
print('min value: ',matrix.min())
print('max value: ',matrix.max())

[[0.62069341 0.19799325 0.18798846 0.61924864 0.36042429 0.74684872
  0.33125165 0.51266526 0.02323987 0.67715246]
 [0.51961994 0.42757476 0.48061053 0.18008725 0.54593732 0.51574039
  0.88369375 0.0335481  0.91909236 0.13597779]
 [0.22653279 0.47968546 0.97201875 0.72120313 0.03311835 0.97693234
  0.04411824 0.42949108 0.01353128 0.98650814]
 [0.17729666 0.58943093 0.79113695 0.51651605 0.60873907 0.29534409
  0.79915855 0.87293144 0.87261119 0.79398967]
 [0.86122205 0.01078419 0.5611258  0.96808922 0.20937961 0.30849987
  0.58045217 0.39268325 0.31530102 0.22880664]
 [0.60478624 0.21500342 0.8009728  0.37378472 0.06622361 0.41462718
  0.92603146 0.42015115 0.50593288 0.73971264]
 [0.57775767 0.73646239 0.70123821 0.81595255 0.38561034 0.77408536
  0.65879634 0.28859931 0.44850996 0.40187502]
 [0.09299923 0.23979983 0.41505404 0.80934175 0.27467518 0.11686222
  0.14012959 0.37631898 0.58207979 0.17725298]
 [0.27705713 0.85695993 0.38910638 0.74552323 0.12868103 0.80547106
  0.73763624

**13. Create a random vector of size 30 and find the mean value**


In [13]:
random_vector=np.random.random((30))
print(random_vector)
print("Mean value: ",random_vector.mean())

[0.55802554 0.21051734 0.95136899 0.80811458 0.38585463 0.39606892
 0.95537884 0.84077958 0.8987292  0.13287056 0.49398145 0.06770732
 0.66996887 0.21875137 0.21057405 0.82947422 0.67521997 0.75417611
 0.75684029 0.95631034 0.37275374 0.61857973 0.86297463 0.30627728
 0.4059479  0.82148869 0.05742368 0.66073646 0.95738978 0.12965451]
Mean value:  0.5654646190136685


**14. Create a 2d array with 1 on the border and 0 inside**

In [14]:
d = np.ones((4,4))
d[1:3,1:3]=0
print(d)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**15. How to add a border (filled with 0's) around an existing array?**

In [15]:
e = np.zeros((4,4))
e[1:3,1:3]=1
print(e)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


**16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

**Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]**

**i Get 13**

**ii get first row only**

**iii get 3rd column only**

**iv get [2, 4, 6]**

**v replace 13 by 20**

In [18]:
#1
arr=np.array([[ 1,2, 3 ,4 ,5, 6, 7] ,[ 8, 9, 10, 11, 12, 13, 14]])
print("To get 13: ",arr[1,5])

To get 13:  13


In [20]:
#2 
print('To get first row',arr[0])


To get first row [1 2 3 4 5 6 7]


In [24]:
#3
print('To get third column: ',arr[:,2])

To get third column:  [ 3 10]


In [27]:
#4
print("To get 2,4,6: ",arr[0,1:7:2])

To get 2,4,6:  [2 4 6]


In [32]:
#5
arr[1,5]=20
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**17 How to Convert a 1D array to a 2D array with 2 rows**

In [33]:
oneD = np.random.random(4)
oneD = oneD.reshape(2,2)
print(oneD)

[[0.23564285 0.36227527]
 [0.40720727 0.18007223]]


**18 Create the following pattern without hardcoding. Use only numpy functions and the below input array a**

**Input: a = np.array([1,2,3])**`

**Desired Output:**

**array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])**

In [37]:
 a = np.array([1,2,3])
 a=np.append(np.repeat(a,3),np.tile(a,3))
 print(a)
 #repeat for element-wise and tile for axis-wise. Append adds to the end of the array

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**19) Write a program to show how Numpy taking less memory compared to Python List?**

In [38]:
l=range(1000)
import sys
a=10
print("Size of list :",sys.getsizeof(a)*len(l))
a1=np.arange(1000)
print("Size of nupy array",a1.size*a1.itemsize)

Size of list : 28000
Size of nupy array 8000


**20) Write a program to show how Numpy taking less time compared to Python List?**

In [39]:
import time
import sys
size=1000000
l1=range(size)
l2=range(size)
n1=np.arange(size)
n2=np.arange(size)
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("time taken by list :",(time.time()-start)*1000)
start=time.time()
res1=n1+n2
print("time taken by numpy array :",(time.time()-start)*1000)

time taken by list : 137.34030723571777
time taken by numpy array : 4.0073394775390625
